project_name: inaccel-docker

before:
  hooks:
  - go mod download
builds:
- binary: docker-inaccel
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  main: ./cmd

archives:
- files:
  - none*
  id: archive
  name_template: "{{ .Os }}-{{ .Arch }}"
changelog:
  filters:
    exclude:
    - '\[APP\]'
checksum:
  name_template: checksums.txt
nfpms:
- bindir: /usr/libexec/docker/cli-plugins
  description: Simplifying FPGA management in Docker
  file_name_template: "{{ .ConventionalFileName }}"
  formats:
  - deb
  - rpm
  homepage: https://inaccel.com
  license: Apache-2.0
  maintainer: InAccel <info@inaccel.com>
  vendor: InAccel
