project_name: inaccel-docker

before:
  hooks:
  - go mod download
builds:
- binary: docker-inaccel
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  main: cmd/main.go

archives:
- files:
  - none*
  id: archive
  name_template: "{{ .Os }}-{{ .Arch }}"
changelog:
  filters:
    exclude:
    - '\[APP\]'
checksum:
  name_template: checksums.txt
nfpms:
- bindir: /usr/libexec/docker/cli-plugins
  description: Simplifying FPGA management in Docker
  formats:
  - deb
  - rpm
  homepage: https://inaccel.com
  license: Apache-2.0
  maintainer: InAccel <info@inaccel.com>
  overrides:
    deb:
      file_name_template: "{{ .ProjectName }}_{{ .RawVersion }}_{{ .Arch }}"
    rpm:
      file_name_template: "{{ .ProjectName }}-{{ .RawVersion }}-1.{{ .Arch }}"
      replacements:
        amd64: x86_64
  vendor: InAccel
