services:
  coral:
    depends_on:
      mkrt:
        condition: service_completed_successfully
    environment:
      FPGAS: ${coral_fpgas}
      HTTPS_PROXY: ${coral_httpsProxy}
      LICENSE: ${license}
      LOG_LEVEL: ${coral_logLevel}
    image: ${coral_image}:${coral_tag}
    labels:
      com.inaccel.docker.default-exec-command: console
      com.inaccel.docker.default-exec-service: True
      com.inaccel.docker.default-logs-service: True
    ports:
    - ${coral_port:-0}:55677
    privileged: true
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${XDG_STATE_HOME:-/var/lib}/inaccel:/var/lib/inaccel:rslave
    - runtimes:/var/opt/inaccel/runtimes:ro
  driver:
    environment:
      DRIVER_SYSROOT_DIR: /host
    image: ${driver_image}:${driver_tag}
    network_mode: host
    pid: host
    privileged: true
    profiles:
    - disabled
    restart: on-failure
    volumes:
    - /:/host
  mkrt:
    environment:
      MKRT_CONFIG_PATH: ${XDG_CONFIG_HOME:-/etc}/inaccel/runtimes
      MKRT_SYSROOT_DIR: /host
    image: ${mkrt_image}:${mkrt_tag}
    restart: on-failure
    volumes:
    - /:/host:ro
    - runtimes:/var/opt/inaccel/runtimes
  monitor:
    image: ${monitor_image}:${monitor_tag}
    ports:
    - ${monitor_port:-0}:19999
    restart: always
volumes:
  runtimes:
