services:
  coral:
    depends_on:
      mkrt:
        condition: service_completed_successfully
    environment:
      FPGAS: ${coral_fpgas}
      HTTPS_PROXY: ${coral_httpsProxy}
      LICENSE: ${license:?The license variable is not set.}
      LOG_LEVEL: ${coral_logLevel}
    image: ${coral_image}:${coral_tag}
    labels:
      com.inaccel.docker.default-exec-command: console
      com.inaccel.docker.default-exec-service: True
      com.inaccel.docker.default-logs-service: True
    ports:
    - ${coral_port}:55677
    privileged: true
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${root_state}:/var/lib/inaccel:rslave
    - ${root_data}:/var/opt/inaccel
  mkrt:
    environment:
      MKRT_CONFIG_PATH: ${root_config}/runtimes
      MKRT_SYSROOT_DIR: /host
    image: ${mkrt_image}:${mkrt_tag}
    restart: on-failure
    volumes:
    - /:/host:ro
    - ${root_data}/runtimes:/var/opt/inaccel/runtimes
  monitor:
    image: ${monitor_image}:${monitor_tag}
    ports:
    - ${monitor_port}:19999
    restart: always
