name: dockerhub
on:
  push:
    paths:
    - configs/*/VERSION
jobs:
  configs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Get changed VERSION files
      id: changed-files
      uses: tj-actions/changed-files@v1.0.2
      with:
        separator: ','
        files: configs/*/VERSION
    - name: List all modified configs
      id: matrix
      run: |
        ALL_MODIFIED_FILES=${{ steps.changed-files.outputs.all_modified_files }}
        for VERSION in ${ALL_MODIFIED_FILES//,/ }; do
            CONFIG="${CONFIG:+${CONFIG}, }\"$(basename $(dirname ${VERSION}))\""
        done
        echo "::set-output name=config::[${CONFIG}]"
    outputs:
      matrix: ${{ steps.matrix.outputs.config }}
  pipeline:
    runs-on: ubuntu-latest
    needs: configs
    if: ${{ !contains(needs.configs.outputs.matrix, '[]') }}
    strategy:
      matrix:
        config: ${{ fromJson(needs.configs.outputs.matrix) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read ${{ matrix.config }} VERSION file
      run: echo VERSION=$(cat configs/${{ matrix.config }}/VERSION) >> ${GITHUB_ENV}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: configs/${{ matrix.config }}
        push: true
        tags: |
          inaccel/${{ matrix.config }}:latest
          inaccel/${{ matrix.config }}:${{ env.VERSION }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker images

          - `docker pull inaccel/${{ matrix.config }}:${{ env.VERSION }}`
        tag_name: ${{ matrix.config }}-${{ env.VERSION }}
