name: dockerhub
on:
  push:
    paths:
    - configs/*/VERSION
jobs:
  configs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changed VERSION files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ','
        files: configs/*/VERSION
    - name: List all modified configs
      id: matrix
      run: |
        ALL_MODIFIED_FILES=${{ steps.changed-files.outputs.all_modified_files }}
        for VERSION in ${ALL_MODIFIED_FILES//,/ }; do
            CONFIG="${CONFIG:+${CONFIG}, }\"$(basename $(dirname ${VERSION}))\""
        done
        echo "config=[${CONFIG}]" >> ${GITHUB_OUTPUT}
    outputs:
      matrix: ${{ steps.matrix.outputs.config }}
  pipeline:
    runs-on: ubuntu-latest
    needs: configs
    if: ${{ !contains(needs.configs.outputs.matrix, '[]') }}
    strategy:
      matrix:
        config: ${{ fromJson(needs.configs.outputs.matrix) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Read ${{ matrix.config }} VERSION file
      run: echo VERSION=$(cat configs/${{ matrix.config }}/VERSION) >> ${GITHUB_ENV}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        flavor: latest=true
        images: inaccel/${{ matrix.config }}
        labels: |
          org.opencontainers.image.authors=InAccel <info@inaccel.com>
          org.opencontainers.image.title=${{ matrix.config }}
          org.opencontainers.image.url=https://inaccel.com
          org.opencontainers.image.vendor=InAccel
        tags: ${{ env.VERSION }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: configs/${{ matrix.config }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker images

          - `docker pull ${{ fromJSON(steps.meta.outputs.json).tags[0] }}`
        tag_name: ${{ matrix.config }}-${{ steps.meta.outputs.version }}
