name: release
on:
  push:
    tags:
    - v*.*.*
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Release binaries
      uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Debian
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: deb
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: dist/*.deb
    - name: Push RPM
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: rpm
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: dist/*.rpm
